### PR TITLE
Add basic schedule setup

### PR DESCRIPTION
**Pull request by tombruijn**
Edit the YAML to add or update a talk.

## Screenshots

Desktop view:
image
Mobile view
Screen Shot 2020-08-14 at 16 23 32

### CODE REVIEW

**Comment by FloorD** [comment]
Screenshot (854)

**Comment by FloorD** [comment]
Yukihiro Matsumoto - Ruby3 and beyond	
Ruby3 is coming! The creator of the language himself explains what is coming with Ruby3. In addition, what will happen after Ruby3.0!	

Penelope Phippen - Building Rubyfmt	
In this talk I'll discuss Rubyfmt, a work in progress Ruby autoformatter. Why I'm building it, and how it differs from Rubocop, the closest similar tool that you might be familiar with. I'll get deep in to the weeds on some of the technical challenges of building a system like this, and what the overall goals for the project are.	

Tetiana Chupryna - Ruby + OpenGL = infinite abilities	
In this talk we’ll explore what can we create using Ruby and OpenGL. We’ll talk about drawing pictures, designing animations and building interfaces. You’ll learn about the basics of OpenGL and eventually, how you can build your own game engine.	
		
Tom de Bruijn - Git is about communication	
Git is about talking to your team. It’s about talking to yourself, from the future. What about that colleague who hasn’t even joined the team yet? Yes, them too. But how to be "good at Git"?

**Comment by tombruijn** [comment]
@FloorD @raytalks I've updated the PR with the schedule so far. Also make some improvements to mention which day, time and timezone the event takes place in. What do you think?

**Comment by FloorD** [comment]
LGTM. Please merge, I have stuffz to add.

**Pull request merged**
